kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-cockroachdb-operator
  namespace: {{ .Release.Namespace }}
  labels:
    operator: rook
    storage-backend: cockroachdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-cockroachdb-operator
subjects:
  - kind: ServiceAccount
    name: rook-cockroachdb-operator
    namespace: {{ .Release.Namespace }}